
import "./globals.css";
   

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (  
    <html lang="en">
<link rel="stylesheet" href="/bootstrap-icons-1.10.5/font/bootstrap-icons.css" />
      <body className="scroll-smooth m-0 p-0 ">
    
        {children}

        </body>
    </html>  
  );
}
