
import "./globals.css";
   

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (  
    <html lang="en">
<script defer src="https://widgets.coingecko.com/gecko-coin-price-static-headline-widget.js"></script>

      <body className="scroll-smooth">
    
        {children}

        </body>
    </html>  
  );
}
